version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_clients
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_backend_clients
    ports:
      - "3306:3306"